### ISSUE TITLE
Whiskey details and menu order

### ISSUE THREAD

**Issue by Mosspiglet68** [divisiblebyzero-uk/WhiskeyTrader#2]
Text has spaces removed, sometimes, upon saving edited details.

Can we reorder the menu tabs in this order - 
Whiskeys, Prices, Trades, Postions, Admin, account

xxx

**Comment by pinkius** [comment]
I think I've found what caused this - the download/exporter on the admin screen was stripping the spaces... I've fixed that but there might be other places that it's doing that. Please raise a further issue if you re-encounter it after the new version is live on the website.
