### ISSUE TITLE
Updating of Mkt price

### ISSUE THREAD

**Issue by Mosspiglet68** [divisiblebyzero-uk/WhiskeyTrader#3]
The  Whiskey Holdings page is not updating the market price. Eg: Rosebank bought at £25, latest priced entered (Jan 21) is £175. but it's showing as Mkt Price £25. Bushmills Distillery Reserve should show as £43 but is still showing as £40.  NIkka should be showing as £47 not £44 (others haven't changed in price so wont change anyway)

**Comment by pinkius** [comment]
Handy query: 
SELECT w.jsondata->'$.name', wp.jsondata->'$.date', wp.jsondata->'$.price' FROM whiskeyprices wp, whiskeys w where w.id = wp.jsondata->'$.whiskeyId'
